apiVersion: v1
kind: Service
metadata:
  labels:
    app: collectibles
  name: collectibles
  namespace: pacman
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: collectibles
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectibles
  namespace: pacman
spec:
  selector:
    matchLabels:
      app: collectibles
  template:
    metadata:
      labels:
        app: collectibles
      namespace: pacman
    spec:
      containers:
      - name: collectibles
        image: pacman-collectibles:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
