apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: pacman
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pacman
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      namespace: pacman
    spec:
      hostAliases:
      - ip: "192.168.99.100"
        hostnames:
        - "pacman.prod"
      containers:
      - name: backend
        image: pacman-backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
